# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.2.4
_src_path: gh:algorandfoundation/algokit-python-template
author_email: 114148836+meetmthosar@users.noreply.github.com
author_name: meetmthosar
contract_name: mutable_smart_nft
deployment_language: python
preset_name: production
project_name: arc-19-20

